[package]
org = "ballerinax"
name = "azure_storage_service"
version = "0.2.0"
export= ["azure_storage_service", "azure_storage_service.blobs", "azure_storage_service.files", "azure_storage_service.utils"]
authors = ["Ballerina"]
keywords = ["azure", "storage", "blob", "file"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-storage-service"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
